---
title: 'Pessoas e medidas'
subtitle: 'Recolher dados dos alunos'
author: 'fnaufel'
email: 'https://fnaufel.github.io/'
date: '   (v. `r format(Sys.Date(), "%d/%m/%Y")`)'
lang: 'pt-br'

output: 
  # To install these output formats, run
  #   install.packages("devtools")
  #   devtools::install_github("fnaufel/fnaufelRmd")
  fnaufelRmd::html_report:
    []
---

```{r setup, include=FALSE}
# The next command configures MANY things and loads quite a few packages.
# 
# If you want to see what's being done, execute 
# 
#   cat(
#     system.file(
#       "rmarkdown/resources/R/_common_report.R", 
#       package = "fnaufelRmd"
#     )
#   )
# 
# to find out the location of the file. Then open the file.
# 
# If you want to change the configuration, copy the file, edit it, and
# source it instead of the package file. 
# 
# Or simply write your commands here in this code chunk.

source(
  system.file(
    "rmarkdown/resources/R/_common_report.R",
    package = "fnaufelRmd"
  )
)
```


# Recolher dados

```{r eval=FALSE}
origens <- list.files(
  './dados/dados-dos-alunos',
  full.names = TRUE,
  recursive = TRUE
) 

dest <- origens %>% 
  map_chr(
    function(x) {
      
      nome <- substring(x, nchar('./dados/dados-dos-alunos/ '))
      
      inicio <- nome %>% 
        word(end = 2) %>% 
        gsub(' ', '_', ., fixed = TRUE)
      
      pos <- nome %>% str_locate('/[^/]+\\.csv')
      fim <- str_sub(nome, pos + 1)
      
      paste0('./dados/dados-dos-alunos/', inicio, '_', fim)
    }
  )
```

```{r eval=FALSE}
origens
```

```{r eval=FALSE}
dest
```

```{r eval=FALSE}
file.copy(
  origens, dest  
)
```


```{r eval=FALSE}
nomes <- origens %>% 
  str_sub(nchar('./dados/dados-dos-alunos/ ')) %>% 
  str_extract('^[^_]+') %>% 
  gsub(' ', '_', .) %>% 
  unique()
```


```{r eval=FALSE}
alunos <- c(
  "Bruno_Dos_Santos_Alves", 
  "Douglas_Mareli_Lopes", 
  "Felipe_Ferreira_Santos_Floret", 
  "Fernando_Castilho_Vargas", 
  "Gabriel_Dos_Santos_Ribeiro", 
  "Gabriel_Silva_De_Carvalho", 
  "Leonardo_Da_Costa_Rosa_Pecanha", 
  "Neri_Allemand_Rodrigues", 
  "Rafael_Abrahao_Da_Costa", 
  "Thayna_Marins_Gomes_Alves"
)
```


# Tibbles com todos os dados

```{r}
razao <- read_csv(
  'dados/razao-todos.csv'
)
```

```{r}
sinistrismo <- read_csv(
  'dados/sinistrismo-todos.csv'
)
```

# Dividir em amostras para cada aluno

```{r eval=FALSE}
gerar_df_aluno <- function(nome, razao, sinistrismo, n = 15) {
  
  r_aluno <- razao %>% 
    slice_sample(n = n)
  
  s_aluno <- sinistrismo %>% 
    slice_sample(n = n)
  
  r_aluno %>% 
    write_csv(
      paste0('dados/', nome, '_razao.csv')
    )
  
  s_aluno %>% 
    write_csv(
      paste0('dados/', nome, '_sinistrismo.csv')
    )

}
```

```{r eval=FALSE}
nomes %>% 
  walk(~gerar_df_aluno(., razao, sinistrismo))
```


## Ler dados de Carlos

```{r}
razao_carlos_in <- read_csv(
  'dados/dados-dos-alunos/Carlos/razao-carlos-in.csv'
)

sinistrismo_carlos_in <- read_csv(
  'dados/dados-dos-alunos/Carlos/sinistrismo-carlos-in.csv'
)
```


## Acrescentar às tibbles

```{r}
razao <- razao %>% 
  rbind(razao_carlos_in)
```

```{r}
sinistrismo <- sinistrismo %>% 
  rbind(sinistrismo_carlos_in)
```


## Sortear para Carlos

```{r}
gerar_df_aluno('Carlos_Vinicios', razao, sinistrismo)
```

